import{S as d,i as c}from"./assets/vendor-8c59ed88.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&o(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();function y(a){return a.map(({id:t,webformatURL:s,largeImageURL:o,views:e,likes:r,comments:n,downloads:m,tags:p})=>`
      <a href="${o}" class="card">
         <img class="card__img" src="${s}" alt="${p}" />
         <div class="card__info">
           <p class="card__numbers"><span>Views:</span> ${e}</p>
           <p class="card__numbers"><span>Likes:</span> ${r}</p>
           <p class="card__numbers"><span>Comments:</span> ${n}</p>
           <p class="card__numbers"><span>Downloads:</span> ${m}</p>
         </div>
      </a>
      `).join("")}const g="https://pixabay.com",h="/api/",_="15968525-5a53092c6d62a7b9e458a529a";function b(a){const t=new URLSearchParams({key:_,image_type:"photo",safesearch:!0,orientation:"horizontal",q:a}),s={Accept:"application/json","Content-Type":"application/json","Referrer-Policy":"no-referrer","X-Requested-With":"XMLHttpRequest"},o=`${g}${h}?${t}`;return fetch(o,s).then(e=>{if(console.log(e),!e.ok)throw new Error(`HTTP error! status: ${e.status}`);if(e.status===0)throw new Error("No response from server");return e.json()}).catch(e=>{console.log(e.message),iziToast.error({title:"Error",message:e.message})})}const f=document.querySelector(".form"),i=document.querySelector(".gallery"),E=new d(".gallery a"),l=document.querySelector(".loader"),u=document.querySelector(".loader__overlay"),L=a=>{a.preventDefault(),l.style.display="block",u.style.display="block",setTimeout(()=>{l.style.display="none",u.style.display="none"},1e3);const t=f.elements.search.value.trim();if(!t){c.error({title:"Error",message:"Empty query",messageColor:"#fff"});return}b(t).then(s=>{if(s.hits.length===0)throw i.innerHTML="",new Error("Sorry, there are no images matching your search query. Please try again!");const o=y(s.hits);i.innerHTML=o,E.refresh(),c.success({title:"Success",message:"Images loaded successfully",messageColor:"#fff"})}).catch(s=>{c.error({title:"Error",message:s.message,backgroundColor:"#EF4040",iconColor:"#ffffff",messageColor:"#fff"})})};f.addEventListener("submit",L);
//# sourceMappingURL=commonHelpers.js.map
